[build-system]
requires = ["sip >=5, <6"]
build-backend = "sipbuild.api"

[tool.sip.metadata]
name = "pysensorlib"
version = "0.1"
license = "MIT"

[tool.sip.bindings.pysensorlib]
headers = ["StateReporter.h"]
libraries = ["libStateReporterLib"]
include-dirs = ["lib"]
library-dirs = ["lib"]

