#ifndef STATEREPORTERLIB_STATE_H
#define STATEREPORTERLIB_STATE_H

typedef enum {
    APPLICATION_STATE_NORMAL,
    APPLICATION_STATE_WARNING,
    APPLICATION_STATE_ERROR,
    APPLICATION_STATE_UNKNOWN
} ApplicationState;

#endif //STATEREPORTERLIB_STATE_H
